// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashMessageController from "./flash_message_controller.js"
application.register("flash-message", FlashMessageController)

import MapUpdateController from "./map_update_controller.js"
application.register("map-update", MapUpdateController)

import GeolocationController from "./geolocation_controller.js"
application.register("geolocation", GeolocationController)

import ScrollTopController from "./scroll_top_controller.js"
application.register("scroll-top", ScrollTopController)

import EditThemeController from "./edit_theme_controller.js"
application.register("edit-theme", EditThemeController)

import EditProfileFormController from "./edit_profile_form_controller.js"
application.register("edit-profile-form", EditProfileFormController)
